CREATE TABLE IF NOT EXISTS posts (
    hn_id INTEGER PRIMARY KEY,
    name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS jobs (
    hn_id INTEGER PRIMARY KEY,
    text TEXT NOT NULL,
    by TEXT NOT NULL,
    post_hn_id INTEGER NOT NULL,
    time INTEGER NOT NULL,
    interesting BOOLEAN NOT NULL,
    email_sent BOOLEAN NOT NULL DEFAULT FALSE
);
