name: release

on:
  push:
    branches: [ master ]

defaults:
  run:
    shell: bash

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - uses: extractions/setup-just@v1

      - uses: actions/setup-node@v4
        with:
          node-version: '21'

      - run: just tailwind-build

      - name: install cargo-deb
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-deb

      - run: just build-deb

      - name: release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifactErrorsFailBuild: true
          removeArtifacts: true
          tag: latest
          artifacts: target/release/hnparser,target/debian/*.deb
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: iliabylich/ppa@notify
        with:
          token: ${{ secrets.PPA_TOKEN }}
