name: release

on:
  push:
    branches: [ master ]

defaults:
  run:
    shell: bash

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - uses: actions/setup-node@v4
        with:
          node-version: '21'

      - name: build styles
        run: npm install && npm run build:release

      - name: install cargo-deb
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-deb

      - name: build
        run: cargo deb --deb-revision="$(date +%s)"

      - name: release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifactErrorsFailBuild: true
          removeArtifacts: true
          tag: latest
          artifacts: target/release/hnparser,target/debian/*.deb
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: refresh PPA
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PPA_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/iliabylich/ppa/actions/workflows/refresh.yml/dispatches \
            -d '{"ref":"master"}'
